project:
  type: website
  output-dir: docs

website:
  title: "Postgrowth Futures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Events"
        menu:
        - cost-of-growth.qmd
        - malma-makua-screening.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

